In [175]:
from sympy import latex
import collections
import numpy as np

In [177]:
%run try_uhlig.py

['K']
['C', 'I', 'L', 'Y']
['adm', 'bdm', 'zetaa']
['adm', 'bdm', 'C', 'I', 'K', 'L', 'Y', 'zetaa']
['wa', 'wzetaa']
self.eqns
[Ct*beta*((-delta + 1)*exp(-admt - mua) + Ytp1*alpha/Kt)/Ctp1 - 1, -Lt/(-Lt + 1) + Yt*nu*(-alpha + 1)/(Ct*(-nu + 1)), Ct + It - Yt, -It + Kt - Ktm1*(-delta + 1)*exp(-bdmt - mua), Ktm1**alpha*Lt**(-alpha + 1)*exp(-alpha*(bdmt + mua) + (admt + mua)*(-alpha + 1)) - Yt, rhoa*zetaat + sigmazetaa*wzetaatp1 - zetaatp1, -admt + sigmaa*watp1 + zetaat, -admt + bdmtp1]

self.eqns_non_expec
[-Lt/(-Lt + 1) + Yt*nu*(-alpha + 1)/(Ct*(-nu + 1)), Ct + It - Yt, -It + Kt - Ktm1*(-delta + 1)*exp(-bdmt - mua), Ktm1**alpha*Lt**(-alpha + 1)*exp(-alpha*(bdmt + mua) + (admt + mua)*(-alpha + 1)) - Yt]

self.eqns_expec
[Ct*beta*((-delta + 1)*exp(-admt - mua) + Ytp1*alpha/Kt)/Ctp1 - 1]

self.eqns_z
[rhoa*zetaat + sigmazetaa*wzetaatp1 - zetaatp1, -admt + sigmaa*watp1 + zetaat, -admt + bdmtp1]
[0.0, 0.0, 0.0]
(array([], dtype=int64),)
[1 1 1]

A
[[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]]


Matrix([[0], [

In [178]:
latex_dic_xtp1 = collections.OrderedDict({Ctp1:'C_{t+1}',Itp1:'I_{t+1}',Ktp1:'K_{t+1}',Ltp1:'L_{t+1}',Ytp1:'Y_{t+1}',
                  atp1:'a_{t+1}', zetaatp1:'\zeta_{a,t+1}'})
latex_dic_xt = collections.OrderedDict({Ct:'C_{t}',It:'I_{t}',Kt:'K_{t}',Lt:'L_{t}',Yt:'Y_{t}',
                  at:'a_{t}', zetaat:'\zeta_{a,t}'})
latex_dic_xtm1 = collections.OrderedDict({Ctm1:'C_{t-1}',Itm1:'I_{t-1}',Ktm1:'K_{t-1}',Ltm1:'L_{t-1}',Ytm1:'Y_{t-1}',
                  atm1:'a_{t-1}', zetaatm1:'\zeta_{a,t-1}'})
latex_dic_wtp1 = collections.OrderedDict({watp1:'w_{a,t+1}', wzetaatp1:'w_{\zeta_a, t+1}'})
latex_dic_wt = collections.OrderedDict({wat:'w_{a,t}', wzetaat:'w_{\zeta_a, t}'})
latex_dic_uh_aux = collections.OrderedDict({admt:'adm_{t+1}', admt:'adm_{t}', admtm1:'adm_{t-1}',
                                            bdmt:'bdm_{t+1}', bdmt:'bdm_{t}', bdmtm1:'bdm_{t-1}'})
latex_dic_param = collections.OrderedDict({mua:'\mu_a', rhoa:'\\rho_{a}',sigmaa:'\sigma_{a}', sigmazetaa:'\sigma_{\zeta_a}'})
latex_dic = latex_dic_xtp1
latex_dic.update(latex_dic_xt)
latex_dic.update(latex_dic_xtm1)
latex_dic.update(latex_dic_wtp1)
latex_dic.update(latex_dic_wt)
latex_dic.update(latex_dic_uh_aux)
latex_dic.update(latex_dic_param)

## Inspect the system of equillibrium equations

### Original system

In Uhlig's form, the equations for the exogenous variables ("z") must be in the form $z_{t+1} = N z_t + \epsilon_{t+1}$, this means that, sometimes we need to shift forward these subset of equations and enter them as $0 = N z_t + \epsilon_{t+1} - z_{t+1}$

In [179]:
umodel.ss_solutions_dict

{Y_ss: 0.46073963452599997,
 K_ss: 1.1282868290070001,
 bdm_ss: 0.0,
 zetaa_ss: 0.0,
 I_ss: 0.142840006613,
 adm_ss: 0.0,
 C_ss: 0.31789962791300003,
 L_ss: 0.27476615687400002}

In [180]:
print(latex(umodel.eqns, symbol_names=latex_dic))

\left [ \frac{C_{t} \beta}{C_{t+1}} \left(\left(- \delta + 1\right) e^{- adm_{t} - \mu_a} + \frac{Y_{t+1} \alpha}{K_{t}}\right) - 1, \quad - \frac{L_{t}}{- L_{t} + 1} + \frac{Y_{t} \nu \left(- \alpha + 1\right)}{C_{t} \left(- \nu + 1\right)}, \quad C_{t} + I_{t} - Y_{t}, \quad - I_{t} + K_{t} - K_{t-1} \left(- \delta + 1\right) e^{- bdm_{t} - \mu_a}, \quad K_{t-1}^{\alpha} L_{t}^{- \alpha + 1} e^{- \alpha \left(bdm_{t} + \mu_a\right) + \left(adm_{t} + \mu_a\right) \left(- \alpha + 1\right)} - Y_{t}, \quad \rho_{a} \zeta_{a,t} + \sigma_{\zeta_a} w_{\zeta_a, t+1} - \zeta_{a,t+1}, \quad - adm_{t} + \sigma_{a} w_{a,t+1} + \zeta_{a,t}, \quad - adm_{t} + bdmtp_{1}\right ]


$\left [ \frac{C_{t} \beta}{C_{t+1}} \left(\left(- \delta + 1\right) e^{- adm_{t} - \mu_a} + \frac{Y_{t+1} \alpha}{K_{t}}\right) - 1, \quad - \frac{L_{t}}{- L_{t} + 1} + \frac{Y_{t} \nu \left(- \alpha + 1\right)}{C_{t} \left(- \nu + 1\right)}, \quad C_{t} + I_{t} - Y_{t}, \quad - I_{t} + K_{t} - K_{t-1} \left(- \delta + 1\right) e^{- bdm_{t} - \mu_a}, \quad K_{t-1}^{\alpha} L_{t}^{- \alpha + 1} e^{- \alpha \left(bdm_{t} + \mu_a\right) + \left(adm_{t} + \mu_a\right) \left(- \alpha + 1\right)} - Y_{t}, \quad \rho_{a} \zeta_{a,t} + \sigma_{\zeta_a} w_{\zeta_a, t+1} - \zeta_{a,t+1}, \quad - adm_{t} + \sigma_{a} w_{a,t+1} + \zeta_{a,t}, \quad - adm_{t} + bdmtp_{1}\right ]$


Is this correct?

### Non expectational Block

In [181]:
umodel.eqns_non_expec

[-Lt/(-Lt + 1) + Yt*nu*(-alpha + 1)/(Ct*(-nu + 1)),
 Ct + It - Yt,
 -It + Kt - Ktm1*(-delta + 1)*exp(-bdmt - mua),
 Ktm1**alpha*Lt**(-alpha + 1)*exp(-alpha*(bdmt + mua) + (admt + mua)*(-alpha + 1)) - Yt]

In [182]:
print(latex(umodel.eqns_non_expec, symbol_names=latex_dic))

\left [ - \frac{L_{t}}{- L_{t} + 1} + \frac{Y_{t} \nu \left(- \alpha + 1\right)}{C_{t} \left(- \nu + 1\right)}, \quad C_{t} + I_{t} - Y_{t}, \quad - I_{t} + K_{t} - K_{t-1} \left(- \delta + 1\right) e^{- bdm_{t} - \mu_a}, \quad K_{t-1}^{\alpha} L_{t}^{- \alpha + 1} e^{- \alpha \left(bdm_{t} + \mu_a\right) + \left(adm_{t} + \mu_a\right) \left(- \alpha + 1\right)} - Y_{t}\right ]


$
\left [ - \frac{L_{t}}{- L_{t} + 1} + \frac{Y_{t} \nu \left(- \alpha + 1\right)}{C_{t} \left(- \nu + 1\right)}, \quad C_{t} + I_{t} - Y_{t}, \quad - I_{t} + K_{t} - K_{t-1} \left(- \delta + 1\right) e^{- bdm_{t} - \mu_a}, \quad K_{t-1}^{\alpha} L_{t}^{- \alpha + 1} e^{- \alpha \left(bdm_{t} + \mu_a\right) + \left(adm_{t} + \mu_a\right) \left(- \alpha + 1\right)} - Y_{t}\right ]
$

Is this correct? Yes.

### Expectational Block

In [183]:
umodel.eqns_expec

[Ct*beta*((-delta + 1)*exp(-admt - mua) + Ytp1*alpha/Kt)/Ctp1 - 1]

In [184]:
print(latex(umodel.eqns_expec, symbol_names=latex_dic))

\left [ \frac{C_{t} \beta}{C_{t+1}} \left(\left(- \delta + 1\right) e^{- adm_{t} - \mu_a} + \frac{Y_{t+1} \alpha}{K_{t}}\right) - 1\right ]


$\left [ \frac{C_{t} \beta}{C_{t+1}} \left(\left(- \delta + 1\right) e^{- adm_{t} - \mu_a} + \frac{Y_{t+1} \alpha}{K_{t}}\right) - 1\right ]$

Is this correct? Yes

### Z block

In [185]:
umodel.eqns_z

[rhoa*zetaat + sigmazetaa*wzetaatp1 - zetaatp1,
 -admt + sigmaa*watp1 + zetaat,
 -admt + bdmtp1]

In [186]:
print(latex(umodel.eqns_z, symbol_names=latex_dic))

\left [ \rho_{a} \zeta_{a,t} + \sigma_{\zeta_a} w_{\zeta_a, t+1} - \zeta_{a,t+1}, \quad - adm_{t} + \sigma_{a} w_{a,t+1} + \zeta_{a,t}, \quad - adm_{t} + bdmtp_{1}\right ]


$
\left [ \rho_{a} \zeta_{a,t} + \sigma_{\zeta_a} w_{\zeta_a, t+1} - \zeta_{a,t+1}, \quad - adm_{t} + \sigma_{a} w_{a,t+1} + \zeta_{a,t}, \quad - adm_{t} + bdmtp_{1}\right ]
$

Is this correct? Yes.

## Inspecting the steady state

### SS solutions

In [187]:
umodel.ss_solutions_dict

{Y_ss: 0.46073963452599997,
 K_ss: 1.1282868290070001,
 bdm_ss: 0.0,
 zetaa_ss: 0.0,
 I_ss: 0.142840006613,
 adm_ss: 0.0,
 C_ss: 0.31789962791300003,
 L_ss: 0.27476615687400002}

In [188]:
umodel.ss_residuals

[1.71862524211974e-13,
 -1.94455562763096e-13,
 5.55111512312578e-17,
 -3.07198710913781e-13,
 2.93709501164585e-13,
 0,
 0.0,
 0.0]

## Inspecting unevaluated Jacobians

### variables

In [189]:
umodel.u_x_tp1_sym, umodel.u_x_t_sym, umodel.u_x_tm1_sym

([Ktp1], [Kt], [Ktm1])

In [190]:
umodel.u_y_tp1_sym, umodel.u_y_t_sym

([Ctp1, Itp1, Ltp1, Ytp1], [Ct, It, Lt, Yt])

In [191]:
umodel.u_z_tp1_sym, umodel.u_z_t_sym

([admtp1, bdmtp1, zetaatp1], [admt, bdmt, zetaat])

## Inspecting unevaluated Jacobians

### Non expectational block

A, B

In [192]:
umodel.eqns_non_expec

[-Lt/(-Lt + 1) + Yt*nu*(-alpha + 1)/(Ct*(-nu + 1)),
 Ct + It - Yt,
 -It + Kt - Ktm1*(-delta + 1)*exp(-bdmt - mua),
 Ktm1**alpha*Lt**(-alpha + 1)*exp(-alpha*(bdmt + mua) + (admt + mua)*(-alpha + 1)) - Yt]

In [193]:
umodel.uA_sym

Matrix([
[0],
[0],
[1],
[0]])

In [194]:
umodel.uB_sym

Matrix([
[                                                                                           0],
[                                                                                           0],
[                                                              -(-delta + 1)*exp(-bdmt - mua)],
[Ktm1**alpha*Lt**(-alpha + 1)*alpha*exp(-alpha*(bdmt + mua) + (admt + mua)*(-alpha + 1))/Ktm1]])

In [195]:
umodel.uC_sym[0,:]

Matrix([[-Yt*nu*(-alpha + 1)/(Ct**2*(-nu + 1)), 0, -Lt/(-Lt + 1)**2 - 1/(-Lt + 1), nu*(-alpha + 1)/(Ct*(-nu + 1))]])

In [196]:
umodel.uC_sym[1,:]

Matrix([[1, 1, 0, -1]])

In [197]:
umodel.uC_sym[2,:]

Matrix([[0, -1, 0, 0]])

In [198]:
umodel.uC_sym[3,:]

Matrix([[0, 0, Ktm1**alpha*Lt**(-alpha + 1)*(-alpha + 1)*exp(-alpha*(bdmt + mua) + (admt + mua)*(-alpha + 1))/Lt, -1]])

In [199]:
umodel.uD_sym[0,:]

Matrix([[0, 0, 0]])

In [200]:
umodel.uD_sym[1,:]

Matrix([[0, 0, 0]])

In [201]:
umodel.uD_sym[2,:]

Matrix([[0, Ktm1*(-delta + 1)*exp(-bdmt - mua), 0]])

In [202]:
umodel.uD_sym[3,:]

Matrix([[Ktm1**alpha*Lt**(-alpha + 1)*(-alpha + 1)*exp(-alpha*(bdmt + mua) + (admt + mua)*(-alpha + 1)), -Ktm1**alpha*Lt**(-alpha + 1)*alpha*exp(-alpha*(bdmt + mua) + (admt + mua)*(-alpha + 1)), 0]])

### Expectational Block

In [203]:
umodel.eqns_expec

[Ct*beta*((-delta + 1)*exp(-admt - mua) + Ytp1*alpha/Kt)/Ctp1 - 1]

$F, G, H$

In [204]:
umodel.uF_sym, umodel.uG_sym, umodel.uH_sym

(Matrix([[0]]), Matrix([[-Ct*Ytp1*alpha*beta/(Ctp1*Kt**2)]]), Matrix([[0]]))

J, K

In [205]:
umodel.uJ_sym

Matrix([[-Ct*beta*((-delta + 1)*exp(-admt - mua) + Ytp1*alpha/Kt)/Ctp1**2, 0, 0, Ct*alpha*beta/(Ctp1*Kt)]])

In [206]:
umodel.uK_sym

Matrix([[beta*((-delta + 1)*exp(-admt - mua) + Ytp1*alpha/Kt)/Ctp1, 0, 0, 0]])

L,M

In [207]:
umodel.uL_sym

Matrix([[0, 0, 0]])

In [208]:
umodel.uM_sym

Matrix([[-Ct*beta*(-delta + 1)*exp(-admt - mua)/Ctp1, 0, 0]])

### Z block

In [209]:
umodel.eqns_z

[rhoa*zetaat + sigmazetaa*wzetaatp1 - zetaatp1,
 -admt + sigmaa*watp1 + zetaat,
 -admt + bdmtp1]

In [210]:
umodel.uN_sym

Matrix([
[ 0, 0, rhoa],
[-1, 0,    1],
[-1, 0,    0]])

## Inspecting evaluated Jacobians

In [211]:
np.set_printoptions(precision=2)

In [212]:
umodel.uA_num_ss

array([[ 0.],
       [ 0.],
       [ 1.],
       [ 0.]])

In [213]:
umodel.uB_num_ss

array([[ 0.  ],
       [ 0.  ],
       [-0.87],
       [ 0.15]])

In [214]:
umodel.uB_num_ss

array([[ 0.  ],
       [ 0.  ],
       [-0.87],
       [ 0.15]])

In [215]:
umodel.uC_num_ss

array([[-1.19,  0.  , -1.9 ,  0.82],
       [ 1.  ,  1.  ,  0.  , -1.  ],
       [ 0.  , -1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.07, -1.  ]])

In [216]:
umodel.uD_num_ss

array([[ 0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.99,  0.  ],
       [ 0.29, -0.17,  0.  ]])

In [217]:
umodel.uF_num_ss

array([[ 0.]])

In [218]:
umodel.uG_num_ss

array([[-0.13]])

In [219]:
umodel.uH_num_ss

array([[ 0.]])

In [220]:
umodel.uJ_num_ss

array([[-3.15,  0.  ,  0.  ,  0.31]])

In [221]:
umodel.uK_num_ss

array([[ 3.15,  0.  ,  0.  ,  0.  ]])

In [222]:
umodel.uL_num_ss

array([[ 0.,  0.,  0.]])

In [223]:
umodel.uM_num_ss

array([[-0.86,  0.  ,  0.  ]])

In [224]:
umodel.uN_num_ss

array([[ 0.  ,  0.  ,  0.97],
       [-1.  ,  0.  ,  1.  ],
       [-1.  ,  0.  ,  0.  ]])

In [225]:
foo = [1,2,3]
moo = [41,5]
foo.extend(moo)
foo

[1, 2, 3, 41, 5]

In [226]:
foo.append(moo)